main: yourselvs.DungeonTracker
name: DungeonTracker
version: 1.0
author: yourselvs
description: A dungeon manager to allow servers to have timed dungeon courses.
commands:
    dungeon:
        description: Access to DungeonTracker commands.
        usage: /<command> ?
        aliases: [dgn, dt, dungeontracker]
permissions:
	dungeon.info:
		default: true
	dungeon.join:
		default: true
	dungeon.forcejoin:
		default: false
	dungeon.leaders:
		default: true
	dungeon.history:
		default: false
	dungeon.record:
		default: true
	dungeon.create:
		default: false
	dungeon.param:
		default: false
	dungeon.command:
		default: false